# --------------------------------
# Infra::Docker::Graylog+MongoDB+ElasticSearch
# Docs: https://docs.graylog.org/en/3.3/pages/installation/docker.html
# Github: https://github.com/quantoneinc/Log.Analytics.Graylog.Ansible/
# --------------------------------

version: '3.3'

services:
  # ---------------------------
  # MongoDB::Data
  # Docs: https://hub.docker.com/_/mongo/
  # ---------------------------
  mongodb:
    image: mongo:4.2
    container_name: graylog.mongodb
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - .env.mongo
    networks:
      - d1_graylog
    ports:
      - 27017
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # ---------------------------
  # Elasticsearch::Cache
  # Docs: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  # ---------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: graylog.escache
    restart: always
    volumes:
      - escache:/usr/share/elasticsearch/data
    env_file:
      - .env.escache
    expose:
      - 9200
      - 9300
    networks:
      - d1_graylog
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # ---------------------------
  # Graylog::Production
  # Docs: https://hub.docker.com/r/graylog/graylog/
  # ---------------------------
  graylog:
    image: graylog/graylog:4.2.4-1-jre11
    container_name: graylog.server
    restart: always
    volumes:
      - ./gldata/config:/usr/share/graylog/data/config
    env_file:
      - .env.graylog
    networks:
      - d1_graylog
      - default
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Host:Container
      # Graylog Web Interface and REST API
      - 9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # INGEST TCP
      - 12201:12201
      # INGEST UDP
      - 12201:12201/udp
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

volumes:
  escache:
  gldata:

networks:
  d1_graylog:
    driver: bridge
