# --------------------------------
# Infra::Docker::Graylog+MongoDB+ElasticSearch
# Docs: https://docs.graylog.org/en/3.3/pages/installation/docker.html
# Github: https://github.com/quantoneinc/Log.Analytics.Graylog.Ansible/
# --------------------------------

version: '3.3'

services:
  # ---------------------------
  # MongoDB::Data
  # Docs: https://hub.docker.com/_/mongo/
  # ---------------------------
  mongodb:
    image: mongo:3
    container_name: graylog.mongodb
    restart: always
    volumes:
      - ./mongodb:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - mongo.env
    networks:
      - d1_graylog
    ports:
      - 9052:27017
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # ---------------------------
  # Elasticsearch::Cache
  # Docs: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  # ---------------------------
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    container_name: graylog.escache
    restart: always
    volumes:
      - ./escache:/usr/share/elasticsearch/data
    networks:
      - d1_graylog
    environment:
      - http.host=0.0.0.0
      - http.port=9200
      - transport.tcp.port=9300
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  d1_graylog:
    driver: bridge
